extends Node3D

func greeting(my_name):
	var message = "Hello " + my_name
	# print(message)
	return message
			
func timer(tree, seconds):
	await tree.create_timer(seconds).timeout
	return "timer expired"

func quit(tree):
	tree.quit()
	
# Generated by Gemini
func get_newly_added_lines(old_text: String, new_text: String):
	var old_lines = old_text.split("\n")
	var new_lines = new_text.split("\n")
	var added_lines = ""

	for new_line in new_lines:
		if not new_line in old_lines:
			added_lines += new_line + "\n"
	
	return added_lines
